---
version: "2.1"
services:
  flaresolverr:
    build:
      context: .
      dockerfile: Dockerfile.vnc
      args:
        - VNC_PASSWORD=${VNC_PASSWORD:-vncPass123}
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FILE=${LOG_FILE:-none}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
      - "${VNC_PORT:-5900}:5900"
    volumes:
      - /var/lib/flaresolver:/config
    shm_size: "2g"
    restart: unless-stopped
